apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: frr-k8s-daemon
  namespace: frr-k8s-system
spec:
  template:
    spec:
      containers:
      - name: frr-k8s
        args:
        - "--node-name=$(NODE_NAME)"
        - "--log-level=debug"
        - "--namespace=$(NAMESPACE)"
