{{- if .Values.openperouter.serviceAccounts.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{- include "openperouter.labels" . | nindent 4 }}
    app.kubernetes.io/component: router
    {{- range $key, $value := .Values.openperouter.labels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  name: {{ template "openperouter.router.serviceAccountName" . }}
  namespace: {{ .Release.Namespace | quote }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{- include "openperouter.labels" . | nindent 4 }}
    app.kubernetes.io/component: controller
    {{- range $key, $value := .Values.openperouter.labels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  name: {{ template "openperouter.controller.serviceAccountName" . }}
  namespace: {{ .Release.Namespace | quote }}
{{- end }}