# permissions for end users to view vnis.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: openperouter
    app.kubernetes.io/managed-by: kustomize
  name: vni-viewer-role
rules:
- apiGroups:
  - per.io.openperouter.github.io
  resources:
  - vnis
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - per.io.openperouter.github.io
  resources:
  - vnis/status
  verbs:
  - get
