apiVersion: per.io.openperouter.github.io/v1alpha1
kind: VNI
metadata:
  name: vni-sample
  namespace: openperouter-system
spec:
  asn: 64514
  vrf: red
  vni: 100
  vxlanport: 4789
  localCIDR: 192.169.10.0/24
  localNeighbor:
    - asn: 64515
      address: 192.169.10.0

