// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.3
// source: api/grpc/openperouter.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OpenPERouterService_UpdateAll_FullMethodName             = "/openperouter.v1alpha1.OpenPERouterService/UpdateAll"
	OpenPERouterService_UpdateNodeIndex_FullMethodName       = "/openperouter.v1alpha1.OpenPERouterService/UpdateNodeIndex"
	OpenPERouterService_UpdateTargetNamespace_FullMethodName = "/openperouter.v1alpha1.OpenPERouterService/UpdateTargetNamespace"
)

// OpenPERouterServiceClient is the client API for OpenPERouterService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OpenPERouterServiceClient interface {
	UpdateAll(ctx context.Context, in *UpdateAllRequest, opts ...grpc.CallOption) (*UpdateAllResponse, error)
	UpdateNodeIndex(ctx context.Context, in *UpdateNodeIndexRequest, opts ...grpc.CallOption) (*UpdateNodeIndexResponse, error)
	UpdateTargetNamespace(ctx context.Context, in *UpdateTargetNamespaceRequest, opts ...grpc.CallOption) (*UpdateTargetNamespaceResponse, error)
}

type openPERouterServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOpenPERouterServiceClient(cc grpc.ClientConnInterface) OpenPERouterServiceClient {
	return &openPERouterServiceClient{cc}
}

func (c *openPERouterServiceClient) UpdateAll(ctx context.Context, in *UpdateAllRequest, opts ...grpc.CallOption) (*UpdateAllResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateAllResponse)
	err := c.cc.Invoke(ctx, OpenPERouterService_UpdateAll_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *openPERouterServiceClient) UpdateNodeIndex(ctx context.Context, in *UpdateNodeIndexRequest, opts ...grpc.CallOption) (*UpdateNodeIndexResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateNodeIndexResponse)
	err := c.cc.Invoke(ctx, OpenPERouterService_UpdateNodeIndex_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *openPERouterServiceClient) UpdateTargetNamespace(ctx context.Context, in *UpdateTargetNamespaceRequest, opts ...grpc.CallOption) (*UpdateTargetNamespaceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateTargetNamespaceResponse)
	err := c.cc.Invoke(ctx, OpenPERouterService_UpdateTargetNamespace_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OpenPERouterServiceServer is the server API for OpenPERouterService service.
// All implementations must embed UnimplementedOpenPERouterServiceServer
// for forward compatibility.
type OpenPERouterServiceServer interface {
	UpdateAll(context.Context, *UpdateAllRequest) (*UpdateAllResponse, error)
	UpdateNodeIndex(context.Context, *UpdateNodeIndexRequest) (*UpdateNodeIndexResponse, error)
	UpdateTargetNamespace(context.Context, *UpdateTargetNamespaceRequest) (*UpdateTargetNamespaceResponse, error)
	mustEmbedUnimplementedOpenPERouterServiceServer()
}

// UnimplementedOpenPERouterServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOpenPERouterServiceServer struct{}

func (UnimplementedOpenPERouterServiceServer) UpdateAll(context.Context, *UpdateAllRequest) (*UpdateAllResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateAll not implemented")
}
func (UnimplementedOpenPERouterServiceServer) UpdateNodeIndex(context.Context, *UpdateNodeIndexRequest) (*UpdateNodeIndexResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateNodeIndex not implemented")
}
func (UnimplementedOpenPERouterServiceServer) UpdateTargetNamespace(context.Context, *UpdateTargetNamespaceRequest) (*UpdateTargetNamespaceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateTargetNamespace not implemented")
}
func (UnimplementedOpenPERouterServiceServer) mustEmbedUnimplementedOpenPERouterServiceServer() {}
func (UnimplementedOpenPERouterServiceServer) testEmbeddedByValue()                             {}

// UnsafeOpenPERouterServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OpenPERouterServiceServer will
// result in compilation errors.
type UnsafeOpenPERouterServiceServer interface {
	mustEmbedUnimplementedOpenPERouterServiceServer()
}

func RegisterOpenPERouterServiceServer(s grpc.ServiceRegistrar, srv OpenPERouterServiceServer) {
	// If the following call pancis, it indicates UnimplementedOpenPERouterServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OpenPERouterService_ServiceDesc, srv)
}

func _OpenPERouterService_UpdateAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAllRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OpenPERouterServiceServer).UpdateAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OpenPERouterService_UpdateAll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OpenPERouterServiceServer).UpdateAll(ctx, req.(*UpdateAllRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OpenPERouterService_UpdateNodeIndex_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateNodeIndexRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OpenPERouterServiceServer).UpdateNodeIndex(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OpenPERouterService_UpdateNodeIndex_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OpenPERouterServiceServer).UpdateNodeIndex(ctx, req.(*UpdateNodeIndexRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OpenPERouterService_UpdateTargetNamespace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTargetNamespaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OpenPERouterServiceServer).UpdateTargetNamespace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OpenPERouterService_UpdateTargetNamespace_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OpenPERouterServiceServer).UpdateTargetNamespace(ctx, req.(*UpdateTargetNamespaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OpenPERouterService_ServiceDesc is the grpc.ServiceDesc for OpenPERouterService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OpenPERouterService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "openperouter.v1alpha1.OpenPERouterService",
	HandlerType: (*OpenPERouterServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateAll",
			Handler:    _OpenPERouterService_UpdateAll_Handler,
		},
		{
			MethodName: "UpdateNodeIndex",
			Handler:    _OpenPERouterService_UpdateNodeIndex_Handler,
		},
		{
			MethodName: "UpdateTargetNamespace",
			Handler:    _OpenPERouterService_UpdateTargetNamespace_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/grpc/openperouter.proto",
}
