// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v5.28.3
// source: api/grpc/openperouter.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpdateResponse_Status int32

const (
	UpdateResponse_SUCCESS                 UpdateResponse_Status = 0
	UpdateResponse_FAILURE                 UpdateResponse_Status = 1
	UpdateResponse_NON_RECOVERABLE_FAILURE UpdateResponse_Status = 2
)

// Enum value maps for UpdateResponse_Status.
var (
	UpdateResponse_Status_name = map[int32]string{
		0: "SUCCESS",
		1: "FAILURE",
		2: "NON_RECOVERABLE_FAILURE",
	}
	UpdateResponse_Status_value = map[string]int32{
		"SUCCESS":                 0,
		"FAILURE":                 1,
		"NON_RECOVERABLE_FAILURE": 2,
	}
)

func (x UpdateResponse_Status) Enum() *UpdateResponse_Status {
	p := new(UpdateResponse_Status)
	*p = x
	return p
}

func (x UpdateResponse_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UpdateResponse_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_api_grpc_openperouter_proto_enumTypes[0].Descriptor()
}

func (UpdateResponse_Status) Type() protoreflect.EnumType {
	return &file_api_grpc_openperouter_proto_enumTypes[0]
}

func (x UpdateResponse_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UpdateResponse_Status.Descriptor instead.
func (UpdateResponse_Status) EnumDescriptor() ([]byte, []int) {
	return file_api_grpc_openperouter_proto_rawDescGZIP(), []int{11, 0}
}

type HostMaster struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	AutoCreate    bool                   `protobuf:"varint,3,opt,name=auto_create,json=autoCreate,proto3" json:"auto_create,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HostMaster) Reset() {
	*x = HostMaster{}
	mi := &file_api_grpc_openperouter_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostMaster) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostMaster) ProtoMessage() {}

func (x *HostMaster) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_openperouter_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostMaster.ProtoReflect.Descriptor instead.
func (*HostMaster) Descriptor() ([]byte, []int) {
	return file_api_grpc_openperouter_proto_rawDescGZIP(), []int{0}
}

func (x *HostMaster) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *HostMaster) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *HostMaster) GetAutoCreate() bool {
	if x != nil {
		return x.AutoCreate
	}
	return false
}

type LocalCIDRConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ipv4          string                 `protobuf:"bytes,1,opt,name=ipv4,proto3" json:"ipv4,omitempty"`
	Ipv6          string                 `protobuf:"bytes,2,opt,name=ipv6,proto3" json:"ipv6,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LocalCIDRConfig) Reset() {
	*x = LocalCIDRConfig{}
	mi := &file_api_grpc_openperouter_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocalCIDRConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocalCIDRConfig) ProtoMessage() {}

func (x *LocalCIDRConfig) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_openperouter_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocalCIDRConfig.ProtoReflect.Descriptor instead.
func (*LocalCIDRConfig) Descriptor() ([]byte, []int) {
	return file_api_grpc_openperouter_proto_rawDescGZIP(), []int{1}
}

func (x *LocalCIDRConfig) GetIpv4() string {
	if x != nil {
		return x.Ipv4
	}
	return ""
}

func (x *LocalCIDRConfig) GetIpv6() string {
	if x != nil {
		return x.Ipv6
	}
	return ""
}

type HostSession struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Asn           uint32                 `protobuf:"varint,1,opt,name=asn,proto3" json:"asn,omitempty"`
	HostAsn       uint32                 `protobuf:"varint,2,opt,name=host_asn,json=hostAsn,proto3" json:"host_asn,omitempty"`
	LocalCidr     *LocalCIDRConfig       `protobuf:"bytes,3,opt,name=local_cidr,json=localCidr,proto3" json:"local_cidr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HostSession) Reset() {
	*x = HostSession{}
	mi := &file_api_grpc_openperouter_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostSession) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostSession) ProtoMessage() {}

func (x *HostSession) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_openperouter_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostSession.ProtoReflect.Descriptor instead.
func (*HostSession) Descriptor() ([]byte, []int) {
	return file_api_grpc_openperouter_proto_rawDescGZIP(), []int{2}
}

func (x *HostSession) GetAsn() uint32 {
	if x != nil {
		return x.Asn
	}
	return 0
}

func (x *HostSession) GetHostAsn() uint32 {
	if x != nil {
		return x.HostAsn
	}
	return 0
}

func (x *HostSession) GetLocalCidr() *LocalCIDRConfig {
	if x != nil {
		return x.LocalCidr
	}
	return nil
}

type BFDSettings struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ReceiveInterval  uint32                 `protobuf:"varint,1,opt,name=receive_interval,json=receiveInterval,proto3" json:"receive_interval,omitempty"`
	TransmitInterval uint32                 `protobuf:"varint,2,opt,name=transmit_interval,json=transmitInterval,proto3" json:"transmit_interval,omitempty"`
	DetectMultiplier uint32                 `protobuf:"varint,3,opt,name=detect_multiplier,json=detectMultiplier,proto3" json:"detect_multiplier,omitempty"`
	EchoInterval     uint32                 `protobuf:"varint,4,opt,name=echo_interval,json=echoInterval,proto3" json:"echo_interval,omitempty"`
	EchoMode         bool                   `protobuf:"varint,5,opt,name=echo_mode,json=echoMode,proto3" json:"echo_mode,omitempty"`
	PassiveMode      bool                   `protobuf:"varint,6,opt,name=passive_mode,json=passiveMode,proto3" json:"passive_mode,omitempty"`
	MinimumTtl       uint32                 `protobuf:"varint,7,opt,name=minimum_ttl,json=minimumTtl,proto3" json:"minimum_ttl,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *BFDSettings) Reset() {
	*x = BFDSettings{}
	mi := &file_api_grpc_openperouter_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BFDSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BFDSettings) ProtoMessage() {}

func (x *BFDSettings) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_openperouter_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BFDSettings.ProtoReflect.Descriptor instead.
func (*BFDSettings) Descriptor() ([]byte, []int) {
	return file_api_grpc_openperouter_proto_rawDescGZIP(), []int{3}
}

func (x *BFDSettings) GetReceiveInterval() uint32 {
	if x != nil {
		return x.ReceiveInterval
	}
	return 0
}

func (x *BFDSettings) GetTransmitInterval() uint32 {
	if x != nil {
		return x.TransmitInterval
	}
	return 0
}

func (x *BFDSettings) GetDetectMultiplier() uint32 {
	if x != nil {
		return x.DetectMultiplier
	}
	return 0
}

func (x *BFDSettings) GetEchoInterval() uint32 {
	if x != nil {
		return x.EchoInterval
	}
	return 0
}

func (x *BFDSettings) GetEchoMode() bool {
	if x != nil {
		return x.EchoMode
	}
	return false
}

func (x *BFDSettings) GetPassiveMode() bool {
	if x != nil {
		return x.PassiveMode
	}
	return false
}

func (x *BFDSettings) GetMinimumTtl() uint32 {
	if x != nil {
		return x.MinimumTtl
	}
	return 0
}

type Neighbor struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Asn            uint32                 `protobuf:"varint,1,opt,name=asn,proto3" json:"asn,omitempty"`
	HostAsn        uint32                 `protobuf:"varint,2,opt,name=host_asn,json=hostAsn,proto3" json:"host_asn,omitempty"`
	Address        string                 `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	Port           uint32                 `protobuf:"varint,4,opt,name=port,proto3" json:"port,omitempty"`
	Password       string                 `protobuf:"bytes,5,opt,name=password,proto3" json:"password,omitempty"`
	PasswordSecret string                 `protobuf:"bytes,6,opt,name=password_secret,json=passwordSecret,proto3" json:"password_secret,omitempty"`
	HoldTime       int64                  `protobuf:"varint,7,opt,name=hold_time,json=holdTime,proto3" json:"hold_time,omitempty"`
	KeepaliveTime  int64                  `protobuf:"varint,8,opt,name=keepalive_time,json=keepaliveTime,proto3" json:"keepalive_time,omitempty"`
	ConnectTime    int64                  `protobuf:"varint,9,opt,name=connect_time,json=connectTime,proto3" json:"connect_time,omitempty"`
	EbgpMultiHop   bool                   `protobuf:"varint,10,opt,name=ebgp_multi_hop,json=ebgpMultiHop,proto3" json:"ebgp_multi_hop,omitempty"`
	Bfd            *BFDSettings           `protobuf:"bytes,11,opt,name=bfd,proto3" json:"bfd,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Neighbor) Reset() {
	*x = Neighbor{}
	mi := &file_api_grpc_openperouter_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Neighbor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Neighbor) ProtoMessage() {}

func (x *Neighbor) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_openperouter_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Neighbor.ProtoReflect.Descriptor instead.
func (*Neighbor) Descriptor() ([]byte, []int) {
	return file_api_grpc_openperouter_proto_rawDescGZIP(), []int{4}
}

func (x *Neighbor) GetAsn() uint32 {
	if x != nil {
		return x.Asn
	}
	return 0
}

func (x *Neighbor) GetHostAsn() uint32 {
	if x != nil {
		return x.HostAsn
	}
	return 0
}

func (x *Neighbor) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Neighbor) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *Neighbor) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *Neighbor) GetPasswordSecret() string {
	if x != nil {
		return x.PasswordSecret
	}
	return ""
}

func (x *Neighbor) GetHoldTime() int64 {
	if x != nil {
		return x.HoldTime
	}
	return 0
}

func (x *Neighbor) GetKeepaliveTime() int64 {
	if x != nil {
		return x.KeepaliveTime
	}
	return 0
}

func (x *Neighbor) GetConnectTime() int64 {
	if x != nil {
		return x.ConnectTime
	}
	return 0
}

func (x *Neighbor) GetEbgpMultiHop() bool {
	if x != nil {
		return x.EbgpMultiHop
	}
	return false
}

func (x *Neighbor) GetBfd() *BFDSettings {
	if x != nil {
		return x.Bfd
	}
	return nil
}

type EVPNConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VtepCidr      string                 `protobuf:"bytes,1,opt,name=vtep_cidr,json=vtepCidr,proto3" json:"vtep_cidr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EVPNConfig) Reset() {
	*x = EVPNConfig{}
	mi := &file_api_grpc_openperouter_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EVPNConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EVPNConfig) ProtoMessage() {}

func (x *EVPNConfig) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_openperouter_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EVPNConfig.ProtoReflect.Descriptor instead.
func (*EVPNConfig) Descriptor() ([]byte, []int) {
	return file_api_grpc_openperouter_proto_rawDescGZIP(), []int{5}
}

func (x *EVPNConfig) GetVtepCidr() string {
	if x != nil {
		return x.VtepCidr
	}
	return ""
}

type L2VNI struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vrf           string                 `protobuf:"bytes,1,opt,name=vrf,proto3" json:"vrf,omitempty"`
	Vni           uint32                 `protobuf:"varint,2,opt,name=vni,proto3" json:"vni,omitempty"`
	VxlanPort     uint32                 `protobuf:"varint,3,opt,name=vxlan_port,json=vxlanPort,proto3" json:"vxlan_port,omitempty"`
	HostMaster    *HostMaster            `protobuf:"bytes,4,opt,name=host_master,json=hostMaster,proto3" json:"host_master,omitempty"`
	L2GatewayIp   string                 `protobuf:"bytes,5,opt,name=l2_gateway_ip,json=l2GatewayIp,proto3" json:"l2_gateway_ip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *L2VNI) Reset() {
	*x = L2VNI{}
	mi := &file_api_grpc_openperouter_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *L2VNI) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*L2VNI) ProtoMessage() {}

func (x *L2VNI) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_openperouter_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use L2VNI.ProtoReflect.Descriptor instead.
func (*L2VNI) Descriptor() ([]byte, []int) {
	return file_api_grpc_openperouter_proto_rawDescGZIP(), []int{6}
}

func (x *L2VNI) GetVrf() string {
	if x != nil {
		return x.Vrf
	}
	return ""
}

func (x *L2VNI) GetVni() uint32 {
	if x != nil {
		return x.Vni
	}
	return 0
}

func (x *L2VNI) GetVxlanPort() uint32 {
	if x != nil {
		return x.VxlanPort
	}
	return 0
}

func (x *L2VNI) GetHostMaster() *HostMaster {
	if x != nil {
		return x.HostMaster
	}
	return nil
}

func (x *L2VNI) GetL2GatewayIp() string {
	if x != nil {
		return x.L2GatewayIp
	}
	return ""
}

type L3VNI struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vrf           string                 `protobuf:"bytes,1,opt,name=vrf,proto3" json:"vrf,omitempty"`
	Vni           uint32                 `protobuf:"varint,2,opt,name=vni,proto3" json:"vni,omitempty"`
	VxlanPort     uint32                 `protobuf:"varint,3,opt,name=vxlan_port,json=vxlanPort,proto3" json:"vxlan_port,omitempty"`
	HostSession   *HostSession           `protobuf:"bytes,4,opt,name=host_session,json=hostSession,proto3" json:"host_session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *L3VNI) Reset() {
	*x = L3VNI{}
	mi := &file_api_grpc_openperouter_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *L3VNI) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*L3VNI) ProtoMessage() {}

func (x *L3VNI) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_openperouter_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use L3VNI.ProtoReflect.Descriptor instead.
func (*L3VNI) Descriptor() ([]byte, []int) {
	return file_api_grpc_openperouter_proto_rawDescGZIP(), []int{7}
}

func (x *L3VNI) GetVrf() string {
	if x != nil {
		return x.Vrf
	}
	return ""
}

func (x *L3VNI) GetVni() uint32 {
	if x != nil {
		return x.Vni
	}
	return 0
}

func (x *L3VNI) GetVxlanPort() uint32 {
	if x != nil {
		return x.VxlanPort
	}
	return 0
}

func (x *L3VNI) GetHostSession() *HostSession {
	if x != nil {
		return x.HostSession
	}
	return nil
}

type L3Passthrough struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HostSession   *HostSession           `protobuf:"bytes,1,opt,name=host_session,json=hostSession,proto3" json:"host_session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *L3Passthrough) Reset() {
	*x = L3Passthrough{}
	mi := &file_api_grpc_openperouter_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *L3Passthrough) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*L3Passthrough) ProtoMessage() {}

func (x *L3Passthrough) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_openperouter_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use L3Passthrough.ProtoReflect.Descriptor instead.
func (*L3Passthrough) Descriptor() ([]byte, []int) {
	return file_api_grpc_openperouter_proto_rawDescGZIP(), []int{8}
}

func (x *L3Passthrough) GetHostSession() *HostSession {
	if x != nil {
		return x.HostSession
	}
	return nil
}

type Underlay struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Asn           uint32                 `protobuf:"varint,1,opt,name=asn,proto3" json:"asn,omitempty"`
	RouterIdCidr  string                 `protobuf:"bytes,2,opt,name=router_id_cidr,json=routerIdCidr,proto3" json:"router_id_cidr,omitempty"`
	Neighbors     []*Neighbor            `protobuf:"bytes,3,rep,name=neighbors,proto3" json:"neighbors,omitempty"`
	Nics          []string               `protobuf:"bytes,4,rep,name=nics,proto3" json:"nics,omitempty"`
	Evpn          *EVPNConfig            `protobuf:"bytes,5,opt,name=evpn,proto3" json:"evpn,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Underlay) Reset() {
	*x = Underlay{}
	mi := &file_api_grpc_openperouter_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Underlay) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Underlay) ProtoMessage() {}

func (x *Underlay) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_openperouter_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Underlay.ProtoReflect.Descriptor instead.
func (*Underlay) Descriptor() ([]byte, []int) {
	return file_api_grpc_openperouter_proto_rawDescGZIP(), []int{9}
}

func (x *Underlay) GetAsn() uint32 {
	if x != nil {
		return x.Asn
	}
	return 0
}

func (x *Underlay) GetRouterIdCidr() string {
	if x != nil {
		return x.RouterIdCidr
	}
	return ""
}

func (x *Underlay) GetNeighbors() []*Neighbor {
	if x != nil {
		return x.Neighbors
	}
	return nil
}

func (x *Underlay) GetNics() []string {
	if x != nil {
		return x.Nics
	}
	return nil
}

func (x *Underlay) GetEvpn() *EVPNConfig {
	if x != nil {
		return x.Evpn
	}
	return nil
}

// UpdateAll messages
type UpdateAllRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	L2Vnis         []*L2VNI               `protobuf:"bytes,1,rep,name=l2vnis,proto3" json:"l2vnis,omitempty"`
	L3Vnis         []*L3VNI               `protobuf:"bytes,2,rep,name=l3vnis,proto3" json:"l3vnis,omitempty"`
	L3Passthroughs []*L3Passthrough       `protobuf:"bytes,3,rep,name=l3passthroughs,proto3" json:"l3passthroughs,omitempty"`
	Underlays      []*Underlay            `protobuf:"bytes,4,rep,name=underlays,proto3" json:"underlays,omitempty"`
	ReloaderIp     string                 `protobuf:"bytes,5,opt,name=reloader_ip,json=reloaderIp,proto3" json:"reloader_ip,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateAllRequest) Reset() {
	*x = UpdateAllRequest{}
	mi := &file_api_grpc_openperouter_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAllRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAllRequest) ProtoMessage() {}

func (x *UpdateAllRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_openperouter_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAllRequest.ProtoReflect.Descriptor instead.
func (*UpdateAllRequest) Descriptor() ([]byte, []int) {
	return file_api_grpc_openperouter_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateAllRequest) GetL2Vnis() []*L2VNI {
	if x != nil {
		return x.L2Vnis
	}
	return nil
}

func (x *UpdateAllRequest) GetL3Vnis() []*L3VNI {
	if x != nil {
		return x.L3Vnis
	}
	return nil
}

func (x *UpdateAllRequest) GetL3Passthroughs() []*L3Passthrough {
	if x != nil {
		return x.L3Passthroughs
	}
	return nil
}

func (x *UpdateAllRequest) GetUnderlays() []*Underlay {
	if x != nil {
		return x.Underlays
	}
	return nil
}

func (x *UpdateAllRequest) GetReloaderIp() string {
	if x != nil {
		return x.ReloaderIp
	}
	return ""
}

type UpdateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        UpdateResponse_Status  `protobuf:"varint,1,opt,name=status,proto3,enum=openperouter.v1alpha1.UpdateResponse_Status" json:"status,omitempty"`
	Errors        []string               `protobuf:"bytes,2,rep,name=errors,proto3" json:"errors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateResponse) Reset() {
	*x = UpdateResponse{}
	mi := &file_api_grpc_openperouter_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateResponse) ProtoMessage() {}

func (x *UpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_openperouter_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateResponse.ProtoReflect.Descriptor instead.
func (*UpdateResponse) Descriptor() ([]byte, []int) {
	return file_api_grpc_openperouter_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateResponse) GetStatus() UpdateResponse_Status {
	if x != nil {
		return x.Status
	}
	return UpdateResponse_SUCCESS
}

func (x *UpdateResponse) GetErrors() []string {
	if x != nil {
		return x.Errors
	}
	return nil
}

// UpdateNodeIndex messages
type UpdateNodeIndexRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeIndex     uint32                 `protobuf:"varint,1,opt,name=node_index,json=nodeIndex,proto3" json:"node_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateNodeIndexRequest) Reset() {
	*x = UpdateNodeIndexRequest{}
	mi := &file_api_grpc_openperouter_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateNodeIndexRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateNodeIndexRequest) ProtoMessage() {}

func (x *UpdateNodeIndexRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_openperouter_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateNodeIndexRequest.ProtoReflect.Descriptor instead.
func (*UpdateNodeIndexRequest) Descriptor() ([]byte, []int) {
	return file_api_grpc_openperouter_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateNodeIndexRequest) GetNodeIndex() uint32 {
	if x != nil {
		return x.NodeIndex
	}
	return 0
}

// UpdateTargetNamespace messages
type UpdateTargetNamespaceRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TargetNamespace string                 `protobuf:"bytes,1,opt,name=target_namespace,json=targetNamespace,proto3" json:"target_namespace,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdateTargetNamespaceRequest) Reset() {
	*x = UpdateTargetNamespaceRequest{}
	mi := &file_api_grpc_openperouter_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTargetNamespaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTargetNamespaceRequest) ProtoMessage() {}

func (x *UpdateTargetNamespaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_openperouter_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTargetNamespaceRequest.ProtoReflect.Descriptor instead.
func (*UpdateTargetNamespaceRequest) Descriptor() ([]byte, []int) {
	return file_api_grpc_openperouter_proto_rawDescGZIP(), []int{13}
}

func (x *UpdateTargetNamespaceRequest) GetTargetNamespace() string {
	if x != nil {
		return x.TargetNamespace
	}
	return ""
}

// UpdateReloaderIP messages
type UpdateReloaderIPRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReloaderIp    string                 `protobuf:"bytes,1,opt,name=reloader_ip,json=reloaderIp,proto3" json:"reloader_ip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateReloaderIPRequest) Reset() {
	*x = UpdateReloaderIPRequest{}
	mi := &file_api_grpc_openperouter_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateReloaderIPRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateReloaderIPRequest) ProtoMessage() {}

func (x *UpdateReloaderIPRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_openperouter_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateReloaderIPRequest.ProtoReflect.Descriptor instead.
func (*UpdateReloaderIPRequest) Descriptor() ([]byte, []int) {
	return file_api_grpc_openperouter_proto_rawDescGZIP(), []int{14}
}

func (x *UpdateReloaderIPRequest) GetReloaderIp() string {
	if x != nil {
		return x.ReloaderIp
	}
	return ""
}

var File_api_grpc_openperouter_proto protoreflect.FileDescriptor

const file_api_grpc_openperouter_proto_rawDesc = "" +
	"\n" +
	"\x1bapi/grpc/openperouter.proto\x12\x15openperouter.v1alpha1\"U\n" +
	"\n" +
	"HostMaster\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x1f\n" +
	"\vauto_create\x18\x03 \x01(\bR\n" +
	"autoCreate\"9\n" +
	"\x0fLocalCIDRConfig\x12\x12\n" +
	"\x04ipv4\x18\x01 \x01(\tR\x04ipv4\x12\x12\n" +
	"\x04ipv6\x18\x02 \x01(\tR\x04ipv6\"\x81\x01\n" +
	"\vHostSession\x12\x10\n" +
	"\x03asn\x18\x01 \x01(\rR\x03asn\x12\x19\n" +
	"\bhost_asn\x18\x02 \x01(\rR\ahostAsn\x12E\n" +
	"\n" +
	"local_cidr\x18\x03 \x01(\v2&.openperouter.v1alpha1.LocalCIDRConfigR\tlocalCidr\"\x98\x02\n" +
	"\vBFDSettings\x12)\n" +
	"\x10receive_interval\x18\x01 \x01(\rR\x0freceiveInterval\x12+\n" +
	"\x11transmit_interval\x18\x02 \x01(\rR\x10transmitInterval\x12+\n" +
	"\x11detect_multiplier\x18\x03 \x01(\rR\x10detectMultiplier\x12#\n" +
	"\recho_interval\x18\x04 \x01(\rR\fechoInterval\x12\x1b\n" +
	"\techo_mode\x18\x05 \x01(\bR\bechoMode\x12!\n" +
	"\fpassive_mode\x18\x06 \x01(\bR\vpassiveMode\x12\x1f\n" +
	"\vminimum_ttl\x18\a \x01(\rR\n" +
	"minimumTtl\"\xed\x02\n" +
	"\bNeighbor\x12\x10\n" +
	"\x03asn\x18\x01 \x01(\rR\x03asn\x12\x19\n" +
	"\bhost_asn\x18\x02 \x01(\rR\ahostAsn\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\tR\aaddress\x12\x12\n" +
	"\x04port\x18\x04 \x01(\rR\x04port\x12\x1a\n" +
	"\bpassword\x18\x05 \x01(\tR\bpassword\x12'\n" +
	"\x0fpassword_secret\x18\x06 \x01(\tR\x0epasswordSecret\x12\x1b\n" +
	"\thold_time\x18\a \x01(\x03R\bholdTime\x12%\n" +
	"\x0ekeepalive_time\x18\b \x01(\x03R\rkeepaliveTime\x12!\n" +
	"\fconnect_time\x18\t \x01(\x03R\vconnectTime\x12$\n" +
	"\x0eebgp_multi_hop\x18\n" +
	" \x01(\bR\febgpMultiHop\x124\n" +
	"\x03bfd\x18\v \x01(\v2\".openperouter.v1alpha1.BFDSettingsR\x03bfd\")\n" +
	"\n" +
	"EVPNConfig\x12\x1b\n" +
	"\tvtep_cidr\x18\x01 \x01(\tR\bvtepCidr\"\xb2\x01\n" +
	"\x05L2VNI\x12\x10\n" +
	"\x03vrf\x18\x01 \x01(\tR\x03vrf\x12\x10\n" +
	"\x03vni\x18\x02 \x01(\rR\x03vni\x12\x1d\n" +
	"\n" +
	"vxlan_port\x18\x03 \x01(\rR\tvxlanPort\x12B\n" +
	"\vhost_master\x18\x04 \x01(\v2!.openperouter.v1alpha1.HostMasterR\n" +
	"hostMaster\x12\"\n" +
	"\rl2_gateway_ip\x18\x05 \x01(\tR\vl2GatewayIp\"\x91\x01\n" +
	"\x05L3VNI\x12\x10\n" +
	"\x03vrf\x18\x01 \x01(\tR\x03vrf\x12\x10\n" +
	"\x03vni\x18\x02 \x01(\rR\x03vni\x12\x1d\n" +
	"\n" +
	"vxlan_port\x18\x03 \x01(\rR\tvxlanPort\x12E\n" +
	"\fhost_session\x18\x04 \x01(\v2\".openperouter.v1alpha1.HostSessionR\vhostSession\"V\n" +
	"\rL3Passthrough\x12E\n" +
	"\fhost_session\x18\x01 \x01(\v2\".openperouter.v1alpha1.HostSessionR\vhostSession\"\xcc\x01\n" +
	"\bUnderlay\x12\x10\n" +
	"\x03asn\x18\x01 \x01(\rR\x03asn\x12$\n" +
	"\x0erouter_id_cidr\x18\x02 \x01(\tR\frouterIdCidr\x12=\n" +
	"\tneighbors\x18\x03 \x03(\v2\x1f.openperouter.v1alpha1.NeighborR\tneighbors\x12\x12\n" +
	"\x04nics\x18\x04 \x03(\tR\x04nics\x125\n" +
	"\x04evpn\x18\x05 \x01(\v2!.openperouter.v1alpha1.EVPNConfigR\x04evpn\"\xac\x02\n" +
	"\x10UpdateAllRequest\x124\n" +
	"\x06l2vnis\x18\x01 \x03(\v2\x1c.openperouter.v1alpha1.L2VNIR\x06l2vnis\x124\n" +
	"\x06l3vnis\x18\x02 \x03(\v2\x1c.openperouter.v1alpha1.L3VNIR\x06l3vnis\x12L\n" +
	"\x0el3passthroughs\x18\x03 \x03(\v2$.openperouter.v1alpha1.L3PassthroughR\x0el3passthroughs\x12=\n" +
	"\tunderlays\x18\x04 \x03(\v2\x1f.openperouter.v1alpha1.UnderlayR\tunderlays\x12\x1f\n" +
	"\vreloader_ip\x18\x05 \x01(\tR\n" +
	"reloaderIp\"\xaf\x01\n" +
	"\x0eUpdateResponse\x12D\n" +
	"\x06status\x18\x01 \x01(\x0e2,.openperouter.v1alpha1.UpdateResponse.StatusR\x06status\x12\x16\n" +
	"\x06errors\x18\x02 \x03(\tR\x06errors\"?\n" +
	"\x06Status\x12\v\n" +
	"\aSUCCESS\x10\x00\x12\v\n" +
	"\aFAILURE\x10\x01\x12\x1b\n" +
	"\x17NON_RECOVERABLE_FAILURE\x10\x02\"7\n" +
	"\x16UpdateNodeIndexRequest\x12\x1d\n" +
	"\n" +
	"node_index\x18\x01 \x01(\rR\tnodeIndex\"I\n" +
	"\x1cUpdateTargetNamespaceRequest\x12)\n" +
	"\x10target_namespace\x18\x01 \x01(\tR\x0ftargetNamespace\":\n" +
	"\x17UpdateReloaderIPRequest\x12\x1f\n" +
	"\vreloader_ip\x18\x01 \x01(\tR\n" +
	"reloaderIp2\xbb\x03\n" +
	"\x13OpenPERouterService\x12[\n" +
	"\tUpdateAll\x12'.openperouter.v1alpha1.UpdateAllRequest\x1a%.openperouter.v1alpha1.UpdateResponse\x12g\n" +
	"\x0fUpdateNodeIndex\x12-.openperouter.v1alpha1.UpdateNodeIndexRequest\x1a%.openperouter.v1alpha1.UpdateResponse\x12s\n" +
	"\x15UpdateTargetNamespace\x123.openperouter.v1alpha1.UpdateTargetNamespaceRequest\x1a%.openperouter.v1alpha1.UpdateResponse\x12i\n" +
	"\x10UpdateReloaderIP\x12..openperouter.v1alpha1.UpdateReloaderIPRequest\x1a%.openperouter.v1alpha1.UpdateResponseB/Z-github.com/openperouter/openperouter/api/grpcb\x06proto3"

var (
	file_api_grpc_openperouter_proto_rawDescOnce sync.Once
	file_api_grpc_openperouter_proto_rawDescData []byte
)

func file_api_grpc_openperouter_proto_rawDescGZIP() []byte {
	file_api_grpc_openperouter_proto_rawDescOnce.Do(func() {
		file_api_grpc_openperouter_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_grpc_openperouter_proto_rawDesc), len(file_api_grpc_openperouter_proto_rawDesc)))
	})
	return file_api_grpc_openperouter_proto_rawDescData
}

var file_api_grpc_openperouter_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_grpc_openperouter_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_api_grpc_openperouter_proto_goTypes = []any{
	(UpdateResponse_Status)(0),           // 0: openperouter.v1alpha1.UpdateResponse.Status
	(*HostMaster)(nil),                   // 1: openperouter.v1alpha1.HostMaster
	(*LocalCIDRConfig)(nil),              // 2: openperouter.v1alpha1.LocalCIDRConfig
	(*HostSession)(nil),                  // 3: openperouter.v1alpha1.HostSession
	(*BFDSettings)(nil),                  // 4: openperouter.v1alpha1.BFDSettings
	(*Neighbor)(nil),                     // 5: openperouter.v1alpha1.Neighbor
	(*EVPNConfig)(nil),                   // 6: openperouter.v1alpha1.EVPNConfig
	(*L2VNI)(nil),                        // 7: openperouter.v1alpha1.L2VNI
	(*L3VNI)(nil),                        // 8: openperouter.v1alpha1.L3VNI
	(*L3Passthrough)(nil),                // 9: openperouter.v1alpha1.L3Passthrough
	(*Underlay)(nil),                     // 10: openperouter.v1alpha1.Underlay
	(*UpdateAllRequest)(nil),             // 11: openperouter.v1alpha1.UpdateAllRequest
	(*UpdateResponse)(nil),               // 12: openperouter.v1alpha1.UpdateResponse
	(*UpdateNodeIndexRequest)(nil),       // 13: openperouter.v1alpha1.UpdateNodeIndexRequest
	(*UpdateTargetNamespaceRequest)(nil), // 14: openperouter.v1alpha1.UpdateTargetNamespaceRequest
	(*UpdateReloaderIPRequest)(nil),      // 15: openperouter.v1alpha1.UpdateReloaderIPRequest
}
var file_api_grpc_openperouter_proto_depIdxs = []int32{
	2,  // 0: openperouter.v1alpha1.HostSession.local_cidr:type_name -> openperouter.v1alpha1.LocalCIDRConfig
	4,  // 1: openperouter.v1alpha1.Neighbor.bfd:type_name -> openperouter.v1alpha1.BFDSettings
	1,  // 2: openperouter.v1alpha1.L2VNI.host_master:type_name -> openperouter.v1alpha1.HostMaster
	3,  // 3: openperouter.v1alpha1.L3VNI.host_session:type_name -> openperouter.v1alpha1.HostSession
	3,  // 4: openperouter.v1alpha1.L3Passthrough.host_session:type_name -> openperouter.v1alpha1.HostSession
	5,  // 5: openperouter.v1alpha1.Underlay.neighbors:type_name -> openperouter.v1alpha1.Neighbor
	6,  // 6: openperouter.v1alpha1.Underlay.evpn:type_name -> openperouter.v1alpha1.EVPNConfig
	7,  // 7: openperouter.v1alpha1.UpdateAllRequest.l2vnis:type_name -> openperouter.v1alpha1.L2VNI
	8,  // 8: openperouter.v1alpha1.UpdateAllRequest.l3vnis:type_name -> openperouter.v1alpha1.L3VNI
	9,  // 9: openperouter.v1alpha1.UpdateAllRequest.l3passthroughs:type_name -> openperouter.v1alpha1.L3Passthrough
	10, // 10: openperouter.v1alpha1.UpdateAllRequest.underlays:type_name -> openperouter.v1alpha1.Underlay
	0,  // 11: openperouter.v1alpha1.UpdateResponse.status:type_name -> openperouter.v1alpha1.UpdateResponse.Status
	11, // 12: openperouter.v1alpha1.OpenPERouterService.UpdateAll:input_type -> openperouter.v1alpha1.UpdateAllRequest
	13, // 13: openperouter.v1alpha1.OpenPERouterService.UpdateNodeIndex:input_type -> openperouter.v1alpha1.UpdateNodeIndexRequest
	14, // 14: openperouter.v1alpha1.OpenPERouterService.UpdateTargetNamespace:input_type -> openperouter.v1alpha1.UpdateTargetNamespaceRequest
	15, // 15: openperouter.v1alpha1.OpenPERouterService.UpdateReloaderIP:input_type -> openperouter.v1alpha1.UpdateReloaderIPRequest
	12, // 16: openperouter.v1alpha1.OpenPERouterService.UpdateAll:output_type -> openperouter.v1alpha1.UpdateResponse
	12, // 17: openperouter.v1alpha1.OpenPERouterService.UpdateNodeIndex:output_type -> openperouter.v1alpha1.UpdateResponse
	12, // 18: openperouter.v1alpha1.OpenPERouterService.UpdateTargetNamespace:output_type -> openperouter.v1alpha1.UpdateResponse
	12, // 19: openperouter.v1alpha1.OpenPERouterService.UpdateReloaderIP:output_type -> openperouter.v1alpha1.UpdateResponse
	16, // [16:20] is the sub-list for method output_type
	12, // [12:16] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_api_grpc_openperouter_proto_init() }
func file_api_grpc_openperouter_proto_init() {
	if File_api_grpc_openperouter_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_grpc_openperouter_proto_rawDesc), len(file_api_grpc_openperouter_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_grpc_openperouter_proto_goTypes,
		DependencyIndexes: file_api_grpc_openperouter_proto_depIdxs,
		EnumInfos:         file_api_grpc_openperouter_proto_enumTypes,
		MessageInfos:      file_api_grpc_openperouter_proto_msgTypes,
	}.Build()
	File_api_grpc_openperouter_proto = out.File
	file_api_grpc_openperouter_proto_goTypes = nil
	file_api_grpc_openperouter_proto_depIdxs = nil
}
